# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 18:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInstitutionStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=180, null=True)),
                ('gender', models.CharField(choices=[(b'M', b'Male'), (b'F', b'Female')], max_length=50)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_upload_file', models.BooleanField(default=False)),
                ('can_process_data', models.BooleanField(default=False)),
                ('data_access_rights', models.ManyToManyField(blank=True, to='datasets.Dataset')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='InstitutionLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_logo_url', models.ImageField(blank=True, max_length=150, upload_to=b'institution_logo')),
                ('institution_name', models.CharField(blank=True, default=b'Swirling', max_length=50)),
                ('institution_website', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
