# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='BSValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CAPValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CBAValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CCGValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CMCValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='FRAValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='IBValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PISValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PIValidationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_records', models.CharField(blank=True, max_length=300, null=True)),
                ('successful_records', models.CharField(blank=True, max_length=300, null=True)),
                ('failed_records', models.CharField(blank=True, max_length=300, null=True)),
                ('number_of_fields_passed', models.CharField(blank=True, max_length=350, null=True)),
                ('number_of_fields_failed', models.CharField(blank=True, max_length=350, null=True)),
                ('new_monthly_records', models.CharField(blank=True, max_length=300, null=True)),
                ('record_type', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('pi_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
