# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fileprocessor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheetname', models.FileField(blank=True, max_length=250, null=True, upload_to=b'.')),
                ('dateuploaded', models.DateTimeField(auto_now_add=True)),
                ('excelname', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fileprocessor.FileUploader')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProcessRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordname', models.CharField(blank=True, max_length=200, null=True)),
                ('filepath', models.FileField(blank=True, max_length=250, null=True, upload_to=b'.')),
                ('updatedate', models.DateTimeField(auto_now_add=True)),
                ('processby', models.CharField(blank=True, max_length=160, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TemporaryExcelUploader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel', models.FileField(blank=True, max_length=500, null=True, upload_to=b'legacyuploads')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
