# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branchcode', '0002_auto_20170418_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredheader',
            name='creation_date',
            field=models.CharField(default=b'2017-05-05', max_length=100),
        ),
    ]
