#  currencyisocode.py
#  
#  Copyright 2015 Wangolo Joel <wangolo@developer>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  


class CurrencyCode(object):
    def __init__(self):
        self.currency = (
                        ("AFN","AFGHANISTAN Afghani "),
                        ("EUR","ALAND ISLANDS   Euro    "),
                        ("ALL","ALBANIA Lek "),
                        ("DZD","ALGERIA Algerian Dinar  "),
                        ("USD","AMERICAN SAMOA  US Dollar   "),
                        ("EUR","ANDORRA Euro    "),
                        ("AOA","ANGOLA  Kwanza  "),
                        ("XCD","ANGUILLA    East Caribbean Dollar   "),
                        ("   ","ANTARCTICA  No universal currency"),
                        ("XCD","ANTIGUA AND BARBUDA East Caribbean Dollar   "),
                        ("ARS","ARGENTINA   Argentine Peso  "),
                        ("AMD","ARMENIA Armenian Dram   "),
                        ("AWG","ARUBA   Aruban Florin   "),
                        ("AUD","AUSTRALIA   Australian Dollar   "),
                        ("EUR","AUSTRIA Euro    "),
                        ("AZN","AZERBAIJAN  Azerbaijanian Manat "),
                        ("BSD","BAHAMAS Bahamian Dollar "),
                        ("BHD","BAHRAIN Bahraini Dinar  "),
                        ("BDT","BANGLADESH  Taka    "),
                        ("BBD","BARBADOS    Barbados Dollar "),
                        ("BYR","BELARUS Belarussian Ruble   "),
                        ("EUR","BELGIUM Euro    "),
                        ("BZD","BELIZE  Belize Dollar   "),
                        ("XOF","BENIN   CFA Franc BCEAO "),
                        ("BMD","BERMUDA Bermudian Dollar    "),
                        ("BTN","BHUTAN  Ngultrum    "),
                        ("INR","BHUTAN  Indian Rupee    "),
                        ("BOB","BOLIVIA, PLURINATIONAL STATE OF Boliviano   "),
                        ("BOV","BOLIVIA, PLURINATIONAL STATE OF Mvdol   "),
                        ("USD","BONAIRE, SINT EUSTATIUS AND SABA    US Dollar   "),
                        ("BAM","BOSNIA AND HERZEGOVINA  Convertible Mark    "),
                        ("BWP","BOTSWANA    Pula    "),
                        ("NOK","BOUVET ISLAND   Norwegian Krone "),
                        ("BRL","BRAZIL  Brazilian Real  "),
                        ("USD","BRITISH INDIAN OCEAN TERRITORY  US Dollar   "),
                        ("BND","BRUNEI DARUSSALAM   Brunei Dollar   "),
                        ("BGN","BULGARIA    Bulgarian Lev   "),
                        ("XOF","BURKINA FASO    CFA Franc BCEAO "),
                        ("BIF","BURUNDI Burundi Franc   "),
                        ("KHR","CAMBODIA    Riel    "),
                        ("XAF","CAMEROON    CFA Franc BEAC  "),
                        ("CAD","CANADA  Canadian Dollar "),
                        ("CVE","CABO VERDE  Cabo Verde Escudo   "),
                        ("KYD","CAYMAN ISLANDS  Cayman Islands Dollar   "),
                        ("XAF","CENTRAL AFRICAN REPUBLIC    CFA Franc BEAC  "),
                        ("XAF","CHAD    CFA Franc BEAC  "),
                        ("CLF","CHILE   Unidad de Fomento   "),
                        ("CLP","CHILE   Chilean Peso    "),
                        ("CNY","CHINA   Yuan Renminbi   "),
                        ("AUD","CHRISTMAS ISLAND    Australian Dollar   "),
                        ("AUD","COCOS (KEELING) ISLANDS Australian Dollar   "),
                        ("COP","COLOMBIA    Colombian Peso  "),
                        ("COU","COLOMBIA    Unidad de Valor Real    "),
                        ("KMF","COMOROS Comoro Franc    "),
                        ("XAF","CONGO   CFA Franc BEAC  "),
                        ("CDF","CONGO, DEMOCRATIC REPUBLIC OF THE   Congolese Franc "),
                        ("NZD","COOK ISLANDS    New Zealand Dollar  "),
                        ("CRC","COSTA RICA  Costa Rican Colon   "),
                        ("XOF","COTE D'IVOIRE   CFA Franc BCEAO "),
                        ("HRK","CROATIA Croatian Kuna   "),
                        ("CUC","CUBA    Peso Convertible    "),
                        ("CUP","CUBA    Cuban Peso  "),
                        ("ANG","CURACAO Netherlands Antillean Guilder   "),
                        ("EUR","CYPRUS  Euro    "),
                        ("CZK","CZECH REPUBLIC  Czech Koruna    "),
                        ("DKK","DENMARK Danish Krone    "),
                        ("DJF","DJIBOUTI    Djibouti Franc  "),
                        ("XCD","DOMINICA    East Caribbean Dollar   "),
                        ("DOP","DOMINICAN REPUBLIC  Dominican Peso  "),
                        ("USD","ECUADOR US Dollar   "),
                        ("EGP","EGYPT   Egyptian Pound  "),
                        ("SVC","EL SALVADOR El Salvador Colon   "),
                        ("USD","EL SALVADOR US Dollar   "),
                        ("XAF","EQUATORIAL GUINEA   CFA Franc BEAC  "),
                        ("ERN","ERITREA Nakfa   "),
                        ("EUR","ESTONIA Euro    "),
                        ("ETB","ETHIOPIA    Ethiopian Birr  "),
                        ("EUR","OPEAN UNION  Euro    "),
                        ("FKP","FALKLAND ISLANDS (MALVINAS) Falkland Islands Pound  "),
                        ("DKK","FAROE ISLANDS   Danish Krone    "),
                        ("FJD","FIJI    Fiji Dollar "),
                        ("EUR","FINLAND Euro    "),
                        ("EUR","FRANCE  Euro    "),
                        ("EUR","FRENCH GUIANA   Euro    "),
                        ("XPF","FRENCH POLYNESIA    CFP Franc   "),
                        ("EUR","FRENCH SOUTHERN TERRITORIES Euro    "),
                        ("XAF","GABON   CFA Franc BEAC  "),
                        ("GMD","GAMBIA  Dalasi  "),
                        ("GEL","GEORGIA Lari    "),
                        ("EUR","GERMANY Euro    "),
                        ("GHS","GHANA   Ghana Cedi  "),
                        ("GIP","GIBRALTAR   Gibraltar Pound "),
                        ("EUR","GREECE  Euro    "),
                        ("DKK","GREENLAND   Danish Krone    "),
                        ("XCD","GRENADA East Caribbean Dollar   "),
                        ("EUR","GUADELOUPE  Euro    "),
                        ("USD","GUAM    US Dollar   "),
                        ("GTQ","GUATEMALA   Quetzal "),
                        ("GBP","GUERNSEY    Pound Sterling  "),
                        ("GNF","GUINEA  Guinea Franc    "),
                        ("XOF","GUINEA-BISSAU   CFA Franc BCEAO "),
                        ("GYD","GUYANA  Guyana Dollar   "),
                        ("HTG","HAITI   Gourde  "),
                        ("USD","HAITI   US Dollar   "),
                        ("AUD","HEARD ISLAND AND McDONALD ISLANDS   Australian Dollar   "),
                        ("EUR","HOLY SEE (VATICAN CITY STATE)   Euro    "),
                        ("HNL","HONDURAS    Lempira "),
                        ("HKD","HONG KONG   Hong Kong Dollar    "),
                        ("HUF","HUNGARY Forint  "),
                        ("ISK","ICELAND Iceland Krona   "),
                        ("INR","INDIA   Indian Rupee    "),
                        ("IDR","INDONESIA   Rupiah  "),
                        ("XDR","INTERNATIONAL MONETARY FUND (IMF) SDR (Special Drawing Right) "),
                        ("IRR","IRAN, ISLAMIC REPUBLIC OF   Iranian Rial    "),
                        ("IQD","IRAQ    Iraqi Dinar "),
                        ("EUR","IRELAND Euro    "),
                        ("GBP","ISLE OF MAN Pound Sterling  "),
                        ("ILS","ISRAEL  New Israeli Sheqel  "),
                        ("EUR","ITALY   Euro    "),
                        ("JMD","JAMAICA Jamaican Dollar "),
                        ("JPY","JAPAN   Yen "),
                        ("GBP","JERSEY  Pound Sterling  "),
                        ("JOD","JORDAN  Jordanian Dinar "),
                        ("KZT","KAZAKHSTAN  Tenge   "),
                        ("KES","KENYA   Kenyan Shilling "),
                        ("AUD","KIRIBATI    Australian Dollar   "),
                        ("KPW","KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF  North Korean Won"),
                        ("KRW","KOREA, REPUBLIC OF  Won "),
                        ("KWD","KUWAIT  Kuwaiti Dinar   "),
                        ("KGS","KYRGYZSTAN  Som "),
                        ("LAK","LAO PEOPLE'S DEMOCRATIC REPUBLIC Kip "),
                        ("EUR","LATVIA  Euro    "),
                        ("LBP","LEBANON Lebanese Pound  "),
                        ("LSL","LESOTHO Loti    "),
                        ("ZAR","LESOTHO Rand    "),
                        ("LRD","LIBERIA Liberian Dollar "),
                        ("LYD","LIBYA   Libyan Dinar    "),
                        ("CHF","LIECHTENSTEIN   Swiss Franc "),
                        ("EUR","LITHUANIA   Euro    "),
                        ("EUR","LUXEMBOURG  Euro    "),
                        ("MOP","MACAO   Pataca  "),
                        ("ER ","MACEDONIA, THE FORM"),
                        ("MKD","YUGOSLAV REPUBLIC OF   Denar   "),
                        ("MGA","MADAGASCAR  Malagasy Ariary "),
                        ("MWK","MALAWI  Kwacha  "),
                        ("MYR","MALAYSIA    Malaysian Ringgit   "),
                        ("MVR","MALDIVES    Rufiyaa "),
                        ("XOF","MALI    CFA Franc BCEAO "),
                        ("EUR","MALTA   Euro    "),
                        ("USD","MARSHALL ISLANDS    US Dollar   "),
                        ("EUR","MARTINIQUE  Euro    "),
                        ("MRO","MAURITANIA  Ouguiya "),
                        ("MUR","MAURITIUS   Mauritius Rupee "),
                        ("EUR","MAYOTTE Euro    "),
                        ("XUA","MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP  ADB Unit of Account "),
                        ("MXN","MEXICO  Mexican Peso    "),
                        ("MXV","MEXICO  Mexican Unidad de Inversion (UDI)   "),
                        ("USD","MICRONESIA, FEDERATED STATES OF US Dollar   "),
                        ("MDL","MOLDOVA, REPUBLIC OF    Moldovan Leu    "),
                        ("EUR","MONACO  Euro    "),
                        ("MNT","MONGOLIA    Tugrik  "),
                        ("EUR","MONTENEGRO  Euro    "),
                        ("XCD","MONTSERRAT  East Caribbean Dollar   "),
                        ("MAD","MOROCCO Moroccan Dirham "),
                        ("MZN","MOZAMBIQUE  Mozambique Metical  "),
                        ("MMK","MYANMAR Kyat    "),
                        ("NAD","NAMIBIA Namibia Dollar  "),
                        ("ZAR","NAMIBIA Rand    "),
                        ("AUD","NAURU   Australian Dollar   "),
                        ("NPR","NEPAL   Nepalese Rupee  "),
                        ("EUR","NETHERLANDS Euro    "),
                        ("XPF","NEW CALEDONIA   CFP Franc   "),
                        ("NZD","NEW ZEALAND New Zealand Dollar  "),
                        ("NIO","NICARAGUA   Cordoba Oro "),
                        ("XOF","NIGER   CFA Franc BCEAO "),
                        ("NGN","NIGERIA Naira"),
                        ("NZD","NIUE    New Zealand Dollar  "),
                        ("AUD","NORFOLK ISLAND  Australian Dollar   "),
                        ("USD","NORTHERN MARIANA ISLANDS    US Dollar   "),
                        ("NOK","NORWAY  Norwegian Krone "),
                        ("OMR","OMAN    Rial Omani  "),
                        ("PKR","PAKISTAN    Pakistan Rupee  "),
                        ("USD","PALAU   US Dollar   "),
                        ("   ","PALESTINE, STATE OF No universal currency"),
                        ("PAB","PANAMA  Balboa  "),
                        ("USD","PANAMA  US Dollar   "),
                        ("PGK","PAPUA NEW GUINEA    Kina    "),
                        ("PYG","PARAGUAY    Guarani "),
                        ("PEN","PERU    Nuevo Sol   "),
                        ("PHP","PHILIPPINES Philippine Peso "),
                        ("NZD","PITCAIRN    New Zealand Dollar  "),
                        ("PLN","POLAND  Zloty"),
                        ("EUR","PORTUGAL    Euro"),
                        ("USD","PUERTO RICO US Dollar   "),
                        ("QAR","QATAR   Qatari Rial"),
                        ("EUR","REUNION Euro "),
                        ("RON","ROMANIA New Romanian Leu"),
                        ("RUB","RUSSIAN FEDERATION  Russian Ruble"),
                        ("RWF","RWANDA  Rwanda Franc    "),
                        ("EUR","SAINT BARTHELEMY    Euro "),
                        ("ND ","SAINT HELENA, ASCENSION A"),
                        ("SHP","TRISTAN DA CUNHA   Saint Helena Pound  "),
                        ("XCD","SAINT KITTS AND NEVIS   East Caribbean Dollar   "),
                        ("XCD","SAINT LUCIA East Caribbean Dollar   "),
                        ("EUR","SAINT MARTIN (FRENCH PART)  Euro    "),
                        ("EUR","SAINT PIERRE AND MIQUELON   Euro    "),
                        ("XCD","SAINT VINCENT AND THE GRENADINES    East Caribbean Dollar   "),
                        ("WST","SAMOA   Tala    "),
                        ("EUR","SAN MARINO  Euro    "),
                        ("STD","SAO TOME AND PRINCIPE   Dobra   "),
                        ("SAR","SAUDI ARABIA    Saudi Riyal "),
                        ("XOF","SENEGAL CFA Franc BCEAO "),
                        ("RSD","SERBIA  Serbian Dinar   "),
                        ("SCR","SEYCHELLES  Seychelles Rupee    "),
                        ("SLL","SIERRA LEONE    Leone   "),
                        ("SGD","SINGAPORE   Singapore Dollar    "),
                        ("ANG","SINT MAARTEN (DUTCH PART)   Netherlands Antillean Guilder   "),
                        ("XSU","SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS SUCRE  Sucre   "),
                        ("EUR","SLOVAKIA    Euro    "),
                        ("EUR","SLOVENIA    Euro    "),
                        ("SBD","SOLOMON ISLANDS Solomon Islands Dollar  "),
                        ("SOS","SOMALIA Somali Shilling "),
                        ("ZAR","SOUTH AFRICA    Rand    "),
                        ("   ","SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS No universal currency"),
                        ("SSP","SOUTH SUDAN South Sudanese Pound    "),
                        ("EUR","SPAIN   Euro    "),
                        ("LKR","SRI LANKA   Sri Lanka Rupee "),
                        ("SDG","SUDAN   Sudanese Pound  "),
                        ("SRD","SURINAME    Surinam Dollar  "),
                        ("NOK","SVALBARD AND JAN MAYEN  Norwegian Krone "),
                        ("SZL","SWAZILAND   Lilangeni   "),
                        ("SEK","SWEDEN  Swedish Krona   "),
                        ("CHE","SWITZERLAND WIR Euro    "),
                        ("CHF","SWITZERLAND Swiss Franc "),
                        ("CHW","SWITZERLAND WIR Franc   "),
                        ("SYP","SYRIAN ARAB REPUBLIC    Syrian Pound    "),
                        ("TWD","TAIWAN, PROVINCE OF CHINA   New Taiwan Dollar   "),
                        ("TJS","TAJIKISTAN  Somoni  "),
                        ("TZS","TANZANIA, UNITED REPUBLIC OF    Tanzanian Shilling  "),
                        ("THB","THAILAND    Baht    "),
                        ("USD","TIMOR-LESTE US Dollar   "),
                        ("XOF","TOGO    CFA Franc BCEAO "),
                        ("NZD","TOKELAU New Zealand Dollar  "),
                        ("TOP","TONGA   Pa'anga "),
                        ("TTD","TRINIDAD AND TOBAGO Trinidad and Tobago Dollar  "),
                        ("TND","TUNISIA Tunisian Dinar  "),
                        ("TRY","TURKEY  Turkish Lira    "),
                        ("TMT","TURKMENISTAN    Turkmenistan New Manat  "),
                        ("USD","TURKS AND CAICOS ISLANDS    US Dollar   "),
                        ("AUD","TUVALU  Australian Dollar   "),
                        ("UGX","UGANDA  Uganda Shilling "),
                        ("UAH","UKRAINE Hryvnia "),
                        ("AED","UNITED ARAB EMIRATES    UAE Dirham  "),
                        ("GBP","UNITED KINGDOM  Pound Sterling  "),
                        ("USD","UNITED STATES   US Dollar   "),
                        ("USN","UNITED STATES   US Dollar (Next day)    "),
                        ("USD","UNITED STATES MINOR OUTLYING ISLANDS    US Dollar   "),
                        ("UYI","URUGUAY Uruguay Peso en Unidades Indexadas (URUIURUI)   "),
                        ("UYU","URUGUAY Peso Uruguayo   "),
                        ("UZS","UZBEKISTAN  Uzbekistan Sum  "),
                        ("VUV","VANUATU Vatu    "),
                        ("VEF","VENEZUELA, BOLIVARIAN REPUBLIC OF   Bolivar "),
                        ("VND","VIET NAM    Dong    "),
                        ("USD","VIRGIN ISLANDS (BRITISH)    US Dollar   "),
                        ("USD","VIRGIN ISLANDS (U.S.)   US Dollar   "),
                        ("XPF","WALLIS AND FUTUNA   CFP Franc   "),
                        ("MAD","WESTERN SAHARA  Moroccan Dirham "),
                        ("YER","YEMEN   Yemeni Rial "),
                        ("ZMW","ZAMBIA  Zambian Kwacha  "),
                        ("ZWL","ZIMBABWE    Zimbabwe Dollar "),
                        )
        '''
        ("XBA","ZZ01_Bond Markets Unit European_EURCO   Bond Markets Unit European Composite Unit (EURCO)   "),
        ("XBB","ZZ02_Bond Markets Unit European_EMU-6   Bond Markets Unit European Monetary Unit (E.M.U.-6) "),
        ("XBC","ZZ03_Bond Markets Unit European_EUA-9   Bond Markets Unit European Unit of Account 9 (E.U.A.-9) "),
        ("XBD","ZZ04_Bond Markets Unit European_EUA-17  Bond Markets Unit European Unit of Account 17 (E.U.A.-17)   "),
        ("XTS","ZZ06_Testing_Code   Codes specifically reserved for testing purposes    "),
        ("XXX","ZZ07_No_Currency    The codes assigned for transactions where no currency is involved   "),
        ("XAU","ZZ08_Gold   Gold    "),
        ("XPD","ZZ09_Palladium  Palladium   "),
        ("XPT","ZZ10_Platinum   Platinum    "),
        ("XAG","ZZ11_Silver Silver"),
        )
        '''
    def get_currency(self):
        return self.currency

    def dictify(self):
        self.D = {}
        for c in self.get_currency():
            self.D[c[0]]=c[1]
        return self.D
        
        
def get_currency():
    currency = CurrencyCode()
    return currency.get_currency()
