"""
Django settings for CRB project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import datetime 

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
NOW = datetime.datetime.now()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&!9n63vc)mb^^cz^@9zsp^#l3z14k4f$qek5kfys*f#@9#u0gn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userlogin',
    'datasets',
    'datasetrecords',
    'fileprocessor',
    'processrecords',
    'validators',
    'manual',
    'fraudcategory',
    'branchcode',
    'creditanalysis',
    'creditreports',
    'schedulers',
    'legacysystems',
    'securityrules',
    'util',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'CRB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CRB.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    #'default': {
    #    'ENGINE': 'django.db.backends.sqlite3',
    #    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    #}
    'default':{
        'ENGINE': 'django.db.backends.mysql',
        'NAME': "db_crb", # os.path.join(BASE_DIR, 'db.sqlite3'),
        "USER": "wangolo",
        "PASSWORD":"Wangolo123Joel!@#@",
        "HOST": "localhost",
        "PORT":"3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "swirlingmedia")
STATIC_ROOT=os.path.join(BASE_DIR, "productionstatic")

#PERONAL
LOGIN_URL = "/"
IMAGE_UPLOAD_PATH=os.path.join(STATIC_ROOT, "swirlingmedia")
# Django Suit configuration example
SUIT_CONFIG = {
    # header
     'ADMIN_NAME': "Cred-Start 'root' Administrative interface",
     'HEADER_DATE_FORMAT': 'l, j. F Y',
     'HEADER_TIME_FORMAT': 'H:i',

    # forms
     'SHOW_REQUIRED_ASTERISK': True,  # Default True
     'CONFIRM_UNSAVED_CHANGES': True, # Default True

    # menu
    'SEARCH_URL': '/admin/auth/user/',
    'MENU_ICONS': {
        'sites': 'icon-leaf',
        'auth': 'icon-lock',
    },
    # 'MENU_OPEN_FIRST_CHILD': True, # Default True
    # 'MENU_EXCLUDE': ('auth.group',),
    # 'MENU': (
    #     'sites',
    #     {'app': 'auth', 'icon':'icon-lock', 'models': ('user', 'group')},
    #     {'label': 'Settings', 'icon':'icon-cog', 'models': ('auth.user', 'auth.group')},
    #     {'label': 'Support', 'icon':'icon-question-sign', 'url': '/support/'},
    # ),

    # misc
    'LIST_PER_PAGE': 15
}
# This applys to each and every branch
PI_IDENTIFICATION="PI0001"
BRANCH_IDENTIFICATION_CODE="1001"
BRANCH_NAME="Something Branch Name"

REFERENCE_FORMAT_TWO  = "%Y-%m-%d-%H-%M-%S-%w"
REFERENCE_FORMAT  = "%Y-%m-%d-%H-%S-%w"


#SETTINGS FOR DATA FILTERING
FIRST_DAY_DATE_FORMAT = "%Y, %m, 1"
LAST_DAY_DATE_FORMAT = "%Y, %m, %d"

FIRST_DAY_DATE_FILTER = NOW.strftime(FIRST_DAY_DATE_FORMAT)
LAST_DAY_DATE_FILTER = NOW.strftime(LAST_DAY_DATE_FORMAT)

FIRST_DAY_DATE_FILTER = [ int(x) for x in FIRST_DAY_DATE_FILTER.split(',') ]
LAST_DAY_DATE_FILTER = [ int(x) for x in LAST_DAY_DATE_FILTER.split(',') ]


#SFTP_LOCAL_PATH="/home/jet-client-1/"
SFTP_LOCAL_PATH="/home/ubuntu/"
